export const SEARCH_PODCASTS = 'SEARCH_PODCASTS';
export const PODCASTS_REQUEST = 'REQUEST_PODCASTS';
export const PODCASTS_RECEIVE = 'RECEIVE_PODCASTS';
export const PODCASTS_FAILURE = 'FAILURE_PODCASTS';

export const PODCAST_LOOKUP_REQUEST = 'PODCAST_LOOKUP_REQUEST';
export const PODCAST_LOOKUP_FAILURE = 'PODCAST_LOOKUP_FAILURE';
export const PODCAST_LOOKUP_RECIEVE = 'PODCAST_LOOKUP_RECIEVE';

export const RSS_REQUEST = 'RSS_REQUEST';
export const RSS_RECEIVE = 'RSS_RECEIVE';
export const RSS_FAILURE = 'RSS_FAILURE';

export const CHANGE_PODCAST = 'CHANGE_PODCAST';
export const PLAY_PODCAST = 'PLAY_PODCAST';
export const PAUSE_PODCAST = 'PAUSE_PODCAST';
export const STOP_PODCAST = 'STOP_PODCAST';

export const statusTypes = {
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED'
};

export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
export const SUBSCRIBE = 'SUBSCRIBE_PODCAST';
export const UNSUBSCRIBE = 'UNSUBSCRIBE_PODCAST';
export const SUBSCRIBE_FAILURE = 'SUBSCRIBE_ERROR';
export const UNSUBSCRIBE_FAILURE = 'SUBSCRIBE_FAILURE';
