export const SEARCH_PODCASTS = 'SEARCH_PODCASTS'
export const PODCASTS_REQUEST = 'REQUEST_PODCASTS'
export const PODCASTS_RECEIVE = 'RECEIVE_PODCASTS'
export const PODCASTS_FAILURE = 'FAILURE_PODCASTS'

export const PODCASTS_DETAIL_REQUEST = 'PODCASTS_DETAIL_REQUEST'
export const PODCASTS_DETAIL_RECEIVE = 'PODCASTS_DETAIL_RECEIVE'

export const RSS_REQUEST = 'RSS_REQUEST'
export const RSS_RECEIVE = 'RSS_RECEIVE'
export const RSS_FAILURE = 'RSS_FAILURE'
