export const SEARCH_PODCASTS = 'SEARCH_PODCASTS';
export const PODCASTS_REQUEST = 'REQUEST_PODCASTS';
export const PODCASTS_RECEIVE = 'RECEIVE_PODCASTS';
export const PODCASTS_FAILURE = 'FAILURE_PODCASTS';

export const PODCASTS_DETAIL_REQUEST = 'PODCASTS_DETAIL_REQUEST';
export const PODCASTS_DETAIL_RECEIVE = 'PODCASTS_DETAIL_RECEIVE';

export const RSS_REQUEST = 'RSS_REQUEST';
export const RSS_RECEIVE = 'RSS_RECEIVE';
export const RSS_FAILURE = 'RSS_FAILURE';

export const CHANGE_PODCAST = 'CHANGE_PODCAST';
export const PLAY_PODCAST = 'PLAY_PODCAST';
export const PAUSE_PODCAST = 'PAUSE_PODCAST';
export const STOP_PODCAST = 'STOP_PODCAST';

export const statusTypes = {
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED'
};

export const SUBSCRIBE = 'SUBSCRIBE_PODCAST';
export const UNSUBSCRIBE = 'UNSUBSCRIBE_PODCAST';
